from fpdf import FPDF
import os

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        # Title on top right
        self.cell(0, 10, 'Nexus Strategic Marketing Report', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_fill_color(200, 220, 255) # Light Blue background
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        # Clean up text encoding issues
        clean_body = body.encode('latin-1', 'replace').decode('latin-1')
        self.multi_cell(0, 6, clean_body)
        self.ln()

    def add_visualization(self, image_path, title=""):
        if os.path.exists(image_path):
            self.ln(5)
            self.set_font('Arial', 'B', 12)
            self.cell(0, 10, title, 0, 1, 'C')
            # Fit image to page width (approx 170mm usable)
            self.image(image_path, x=20, w=170) 
            self.ln(10)

def generate_full_report(context_data, image_paths, output_filename):
    pdf = PDFReport()
    pdf.add_page()
    
    # --- TITLE PAGE ---
    pdf.ln(40)
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 10, "Marketing Attribution Strategy", 0, 1, 'C')
    pdf.ln(10)
    pdf.set_font('Arial', '', 14)
    pdf.cell(0, 10, "Generated by Nexus AI", 0, 1, 'C')
    pdf.ln(30)
    
    # --- 1. EXECUTIVE SUMMARY ---
    pdf.chapter_title("1. Executive Summary")
    pdf.chapter_body(context_data.get('executive_summary', "Summary unavailable."))
    
    # --- 2. JOURNEY FLOW (Q Matrix) ---
    pdf.add_page()
    pdf.chapter_title("2. User Journey Analysis")
    pdf.chapter_body(context_data.get('q_matrix_insight', ""))
    if 'q_matrix' in image_paths:
        pdf.add_visualization(image_paths['q_matrix'], "Transition Probability Matrix")

    # --- 3. CONVERSION ANALYSIS (R Matrix) ---
    pdf.add_page()
    pdf.chapter_title("3. Conversion & Drop-off")
    pdf.chapter_body(context_data.get('r_matrix_insight', ""))
    if 'r_matrix' in image_paths:
        pdf.add_visualization(image_paths['r_matrix'], "Absorption Matrix")
    if 'conv_probs' in image_paths:
        pdf.add_visualization(image_paths['conv_probs'], "Conversion Probability per Channel")

    # --- 4. STRATEGIC VALUE (Removal Effects) ---
    pdf.add_page()
    pdf.chapter_title("4. Strategic Channel Value")
    pdf.chapter_body(context_data.get('removal_insight', ""))
    if 'removal' in image_paths:
        pdf.add_visualization(image_paths['removal'], "Removal Effects Analysis")

    pdf.output(output_filename)
    return output_filename